GET http://localhost:3001/api/users

###

POST http://localhost:3001/api/users
Content-Type: application/json

# {
#   "username": "john@example.com",
#   "name": "John Doe",
#   "password": "secret"
# }

{
  "username": "jane@example.com",
  "name": "Jane Doe",
  "password": "secret"
}
