services:
  mongo:
    image: mongo
    # initialization happens in dev environment
    volumes:
      - ./todo-backend/mongo_data:/data/db

  redis:
    image: redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - ./todo-backend/redis_data:/data

  server:
    image: todo-backend
    container_name: todo-backend
    environment:
      - REDIS_URL
      - MONGO_URL
      - NODE_ENV=production

  app:
    image: todo-front
    container_name: todo-front
    environment:
      - NODE_ENV=production
    volumes:
      - static_data:/usr/src/app/dist

  nginx:
    image: nginx:1.20.1
    container_name: reverse-proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/usr/share/nginx/html
    ports:
      - 8080:80
    depends_on:
      - app
      - server

volumes:
  static_data:
