GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "This is a random title",
  "author": "John Doe",
  "url": "example.com/clever-blogpost",
  "likes": 18
}