GET http://localhost:3003/api/blogs

###

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphbmVEIiwiaWQiOiI2NmI5ZjQ0N2RlZWI5MDkxZmY0ZjZhM2IiLCJpYXQiOjE3MjM0NzAzMDIsImV4cCI6MTcyMzQ3MzkwMn0.usAyZxVmyAxh-0l097mtz0siU7TNCn9pIsDUtZjtTag

# {
#   "title": "This is a random title",
#   "author": "John Doe",
#   "url": "example.com/clever-blogpost",
#   "likes": 18
# }

# {
#   "title": "5 ways to make your code more readable",
#   "author": "Lizzy McReadsalot",
#   "url": "example.com/reader-friendly-0245882",
#   "likes": 22
# }

{
  "title": "On inevitability of existential dread",
  "author": "Boring McBore",
  "url": "example.com/dreading",
  "likes": 0
}