GET http://localhost:3003/api/blogs

###

PUT http://localhost:3003/api/blogs/66b9f50b347f8e78d385d388
Content-Type: application/json

{
    "title": "5 ways to make your code more readable",
    "author": "Lizzy McReadsalot",
    "url": "example.com/reader-friendly-0245882",
    "likes": 28,
    "user": "66b9f447deeb9091ff4f6a3b"
}